version: "3.1"
services:

  redis:
    image: redis:alpine
    container_name: laracondominum-redis

  mysql:
    image: mysql:8.0
    container_name: laracondominum-mysql
    working_dir: /application
    volumes:
      - ./backend:/application
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=laracondominum
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - "3306:3306"

  mysql-testing:
    image: mysql:8.0
    container_name: laracondominum-mysql-testing
    working_dir: /application
    volumes:
      - ./backend:/application
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=laracondominum
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - "3307:3306"

  webserver:
    image: nginx:alpine
    container_name: laracondominum-webserver
    working_dir: /application
    volumes:
        - ./backend:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3333:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: laracondominum-php-fpm
    working_dir: /application
    volumes:
      - ./backend:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

